
---
- hosts: yyy
  sudo: yes
    
  # Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
  # Will include all hosts the playbook is run on.
  # Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

  tasks:  
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']      
    tags:
      - setup

  - name: "Set hostname"
    hostname: name={{item}}
    with_items: groups['all']      
    tags:
      - setup

  - name: "Fix ctrl key system-wide"
    lineinfile: dest=/etc/bash.bashrc line='if [ -n "$DISPLAY" ]; then /usr/bin/setxkbmap -option 'ctrl:nocaps' ; fi' state=present
    tags:
      - fixctrl

# fix ctrl key system wide

  roles:
    - { role: ntp, tags: ["ntp"] }                
    - { role: utils, tags: ["utils"] }            
#    - { role: emacs, tags: ["emacs"] }    
#    - { role: dotfiles, tags: ["dotfiles"] }        
