---
- name: Install | Utilities
  apt: pkg={{ item }} state=installed update_cache=false
  with_items:
    - git
    - gnutls-bin


- name: Install | create directory for fixctrl script
  file: path=/home/george/bin state=directory    

- name: Install | copy fixctrl script
  copy: src=/home/george/bin/fixctrl.sh dest=/home/george/bin/fixctrl.sh mode=755
  tags:  
      - fixctrl

- name: "Fix ctrl key system-wide"
  lineinfile: dest=/etc/bash.bashrc line='if [ -n "$DISPLAY" ]; then /usr/bin/setxkbmap -option 'ctrl:nocaps' ; fi' state=present
  tags:
    - fixctrl
        
    
    
