---
- name: Install | Utilities
  apt: pkg={{ item }} state=installed update_cache=false
  with_items:
    - git
    - gnutls-bin

- name: copy script to fix ctrl
        copy: src=/home/george/bin/fixctrl.sh dest=/home/george/bin/fixctrl.sh owner=foo group=foo mode=0644    
    
    
