---
- name: Install packages I use most of the time
  apt: pkg={{ item }} state=installed update_cache=false
  with_items:
    - git
    - chromium-browser
    - gnutls-bin
    - ispell
    - whois
    
    
