#+TITLE: Ansible Setup Scripts
#+DATE: <2015-05-31 17:15:54 Sunday>
#+AUTHOR: George M Jones
#+EMAIL: gmj@pobox.com

* What
  This file documents my experimentation with using [[http://en.wikipedia.org/wiki/Ansible_(software)][Ansible]] to
  automate my system and application configurations.

* Why
  I keep building Virtual Machines, Amazon EC2 instances and, in some
  cases, installing software and operating systems on physical
  machines.   The process is ad hoc, non-repeatable and error prone.
  I want to fix that.

* Who
  [[https://www.linkedin.com/in/mattkaar][Matt Kaar]] originally pointed me at Ansible, and I did some work with
  it in the context of [[http://cert.org][CERT]]'s [[https://stepfwd.cert.org/lms][STEPfwd]] program.  I've since done a
  little bit of work with [[https://www.chef.io/chef/][Chef]] and (thanks again to Matt) too a look
  at the documentation for [[http://saltstack.com/community/][SaltStack]], but in the end, I think I'm
  going to go with Ansible because a) I've used it a bit b) I find
  Chef to be a bit baroque and c) I like the agentless nature of
  ansible ... all you need is the ability to SSH to your victims (er,
  managed boxes).

  See the following for some other comparisons:

  - http://www.scriptrock.com/articles/ansible-vs-chef
  - http://probably.co.uk/puppet-vs-chef-vs-ansible.html

  I will be borrowing from the ansible tutorial at https://serversforhackers.com/an-ansible-tutorial

* When

  - Now.
  - All systems moving forward.

* Where

  - Brand new Ubuntu 14.04.2 (which may date this going forward) VM
    running on my "lab" at home.   Will probably build up "roles" to
    install all my usual suspects, stick the configs on github, and
    use Ansible-ized machines going forward.
  - May move to EC2 instances later

* How
  - Start with a freshly installed Ubuntu 14.04 system
  - Set up SSH and root password on managed system(s)
  - Install ansible on a management system

