---
- hosts: all
  user: root
  vars:
    secondsPerMinute: 60
    secondsPerHour: 3600
    secondsPerDay: 86400
    secondsPerWeek: 604800

  tasks:
  - name: Install requied packages for which order does not matter
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - git
    tags:
      - setup      
    
  - name: Setup | set postfix selections wtihout prompting
    shell: echo postfix postfix/mailname string `hostname` | debconf-set-selections
    register: firstSelection
    tags:
      - setup          

  - name: Setup | second selection
    when: firstSelection|success
    shell: echo postfix postfix/main_mailer_type string 'No configuration' | debconf-set-selections
    register: secondSelection
    tags:
      - setup          
    
  - name: Setup | install postfix
    when: secondSelection|success
    shell: apt-get install -y postfix
    register: postfixInstalled
    tags:
      - setup          

  - name: Setup | install build dependencies for emacs
    when: postfixInstalled
    command: apt-get -y build-dep emacs23
    register: depends
    tags:
      - setup          

# Pull emacs sources, but no more often than once a week
    
  - stat: path=~/git/emacs/ansible.emacs_source_pulled
    register: pulled
    become: no
    tags:
      - pull    
    
  - name: Setup | pull latest emacs sources
    when: depends|success and 
          (not pulled.stat.exists)
    git: repo=https://github.com/emacs-mirror/emacs.git accept_hostkey=true dest=~/git/emacs
    register: src
    become: no
    tags:
      - pull    

  - name: Setup | remember when we last pulled emacs sources
    file: path=~/git/emacs/ansible.emacs_source_pulled  state=touch
    when: src|success and (not src|skipped)
    become: no
    tags:
      - pull


# build from source just pulled.  These take a while

  - name: Setup | autogen
    when: src|success
    command: ./autogen.sh chdir=~/git/emacs
    register: autogen
    become: no
    tags:
      - build
    

  - name: Setup | configure
    when: autogen|success
    command: ./configure chdir=~/git/emacs
    register: configure
    become: no
    tags:
      - build

  - name: Setup | bootstrap
    when: configure|success
    command: make bootstrap chdir=~/git/emacs
    register: bootstrap
    become: no
    tags:
      - build    

  - name: Setup | install
    when: bootstrap|success
    command: make install chdir={{ansible_user_dir}}/git/emacs
    tags:
      - install


    
#./configure
#make bootstrap
#sudo make install
